### ISSUE TITLE
jabber login

### ISSUE THREAD

**Issue by mstbone67a** [formigarafa/robotito#3]
to login your google account must be set to use less secure apps.

**Comment by formigarafa** [comment]
@mstbone67a ,
yes you are right. But after lots of research about it I could find no other way to login to google hangouts (former gtalk) without enabling such access into my google account.
BTW, this is not exactly a issue with jabber login itself, this is more a google authentication issue, as you can see in several jabber clients trying to access a gtalk account need to have the same prerequisites fulfilled to be able to work properly.

Anyway, you still can use it with another jabber service instead of gtalk and keep your google account using all their higher security standards.

I have some ideas to improve the security of the robotito itself, but I would like to listen from some users what they think, first.

If you have any suggestion or if you have any idea on how to improve robotito in any aspect, just drop a line and I can see what I can do.
